<?php
require_once __DIR__ . "/../src/Autoloader.php";

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-11 at 19:05:49.
 */
class PlusTest extends PHPUnit_Framework_TestCase {

    
    function testGetResultSuccess(){
        $plusObject=new Plus(array(1,2));
        $this->assertEquals(3, $plusObject->getResult());
        $plusObject->setOperands(array(5,0));
        $this->assertEquals(5, $plusObject->getResult());
        $plusObject->setOperands(array(5,"2"));
        $this->assertEquals(7, $plusObject->getResult());
    } 
    
    function testGetResultThreeOperandsSuccess(){
        $plusObject=new Plus(array(1,2,3));
        $this->assertEquals(6, $plusObject->getResult());
        $plusObject->setOperands(array(5,0,1));
        $this->assertEquals(6, $plusObject->getResult());
        $plusObject->setOperands(array(5,"2",3));
        $this->assertEquals(10, $plusObject->getResult());
    }  
    
    function testGetResultHexOctBinNumbersSuccess(){
        $plusObject=new Plus(array(0x539,2));
        $this->assertEquals(1339, $plusObject->getResult());
        $plusObject->setOperands(array(02471,-0));
        $this->assertEquals(1337, $plusObject->getResult());
        $plusObject->setOperands(array(0b10100111001,"-2"));
        $this->assertEquals(1335, $plusObject->getResult());
    }
    
    function testGetResultNegativeNumbersSuccess(){
        $plusObject=new Plus(array(-1,2));
        $this->assertEquals(1, $plusObject->getResult());
        $plusObject->setOperands(array(-5,-0));
        $this->assertEquals(-5, $plusObject->getResult());
        $plusObject->setOperands(array(5,"-2"));
        $this->assertEquals(3, $plusObject->getResult());
    } 
    
    function testGetResultExponentialNumbersSuccess(){
        $plusObject=new Plus(array(1e1,2e2));
        $this->assertEquals(210, $plusObject->getResult());
        $plusObject->setOperands(array(5e0,0));
        $this->assertEquals(5, $plusObject->getResult());
    } 
    
    /**
     * @expectedException PHPUnit_Framework_Error
     */
    public function testPHPUnit_Framework_Error()
    {
        $plusObject=new Plus("1");
    } 
    
     /**
     * @expectedException InvalidArgumentException
     */
    public function testConstructorInvalidArgumentException()
    {
        $plusObject=new Plus(array('sss', 1));
    } 

}
