<?php
require_once __DIR__ . "/../src/Autoloader.php";

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-11 at 19:05:49.
 */
class SolverTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Solver
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Solver;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        $this->object = null;
    }
    
    function testSolveSumSuccess(){	     
            $this->assertEquals(3, $this->object->solve(array(1, "Plus", 2)));	
            $this->assertEquals(1, $this->object->solve(array(1, "Plus", 0))); 
            $this->assertEquals(0, $this->object->solve(array(0, "Plus", 0)));   
            $this->assertEquals(5, $this->object->solve(array(3, "Plus", "2")));
    }
    
    function testSolveMultiplicationSuccess(){	     
            $this->assertEquals(2, $this->object->solve(array(1, "Times", 2)));	
            $this->assertEquals(0, $this->object->solve(array(1, "Times", 0))); 
            $this->assertEquals(0, $this->object->solve(array(0, "Times", 0)));   
            $this->assertEquals(6, $this->object->solve(array(3, "Times", "2")));
    }
    
    /**
     * @expectedException PHPUnit_Framework_Error
     */
    public function testPHPUnit_Framework_Error()
    {
        $this->object->solve(1);
    } 
    
     /**
     * @expectedException LengthException
     */
    public function testSolveLengthException()
    {
        $this->object->solve(array(1, "Plus"));
    } 
    
    /**
     * @expectedException InvalidArgumentException
     */
    public function testInvalidArgumentException()
    {
        $this->object->solve(array(1, "Plus", "Plus"));
    } 

}
